import { DE_1_RAW_QUESTIONS_LISTENING } from "./DE_1_RAW_QUESTIONS_LISTENING";
import { DE_2_RAW_QUESTIONS_LISTENING } from "./DE_2_RAW_QUESTIONS_LISTENING";
import { DE_3_RAW_QUESTIONS_LISTENING } from "./DE_3_RAW_QUESTIONS_LISTENING";
import { DE_4_RAW_QUESTIONS_LISTENING } from "./DE_4_RAW_QUESTIONS_LISTENING";
import { DE_5_RAW_QUESTIONS_LISTENING } from "./DE_5_RAW_QUESTIONS_LISTENING";
import { DE_6_RAW_QUESTIONS_LISTENING } from "./DE_6_RAW_QUESTIONS_LISTENING";
import { DE_8_RAW_QUESTIONS_LISTENING } from "./DE_8_RAW_QUESTIONS_LISTENING";
import { DE_7_RAW_QUESTIONS_LISTENING } from "./DE_7_RAW_QUESTIONS_LISTENING";
import { DE_9_RAW_QUESTIONS_LISTENING } from "./DE_9_RAW_QUESTIONS_LISTENING";
import { DE_10_RAW_QUESTIONS_LISTENING } from "./DE_10_RAW_QUESTIONS_LISTENING";
import { DE_11_RAW_QUESTIONS_LISTENING } from "./DE_11_RAW_QUESTIONS_LISTENING";
import { DE_12_RAW_QUESTIONS_LISTENING } from "./DE_12_RAW_QUESTIONS_LISTENING";
import { DE_13_RAW_QUESTIONS_LISTENING } from "./DE_13_RAW_QUESTIONS_LISTENING";
import { DE_14_RAW_QUESTIONS_LISTENING } from "./DE_14_RAW_QUESTIONS_LISTENING";
import { DE_15_RAW_QUESTIONS_LISTENING } from "./DE_15_RAW_QUESTIONS_LISTENING";

export const ALL_RAW_QUESTIONS_LISTENING = [
  ...DE_1_RAW_QUESTIONS_LISTENING,
  ...DE_2_RAW_QUESTIONS_LISTENING,
  ...DE_3_RAW_QUESTIONS_LISTENING,
  ...DE_4_RAW_QUESTIONS_LISTENING,
  ...DE_5_RAW_QUESTIONS_LISTENING,
  ...DE_6_RAW_QUESTIONS_LISTENING,
  ...DE_7_RAW_QUESTIONS_LISTENING,
  ...DE_8_RAW_QUESTIONS_LISTENING,
  ...DE_9_RAW_QUESTIONS_LISTENING,
  ...DE_10_RAW_QUESTIONS_LISTENING,
  ...DE_11_RAW_QUESTIONS_LISTENING,
  ...DE_12_RAW_QUESTIONS_LISTENING,
  ...DE_13_RAW_QUESTIONS_LISTENING,
  ...DE_14_RAW_QUESTIONS_LISTENING,
  ...DE_15_RAW_QUESTIONS_LISTENING,
]