// src/assets/mock-data/all-reading-questions.ts

import { DE_1_RAW_QUESTIONS_READING } from './DE_1_RAW_QUESTIONS_READING';
import { DE_2_RAW_QUESTIONS_READING } from './DE_2_RAW_QUESTIONS_READING';
import { DE_3_RAW_QUESTIONS_READING } from './DE_3_RAW_QUESTIONS_READING';
import { DE_4_RAW_QUESTIONS_READING } from './DE_4_RAW_QUESTIONS_READING';
import { DE_5_RAW_QUESTIONS_READING } from './DE_5_RAW_QUESTIONS_READING';
import { DE_6_RAW_QUESTIONS_READING } from './DE_6_RAW_QUESTIONS_READING';
import { DE_7_RAW_QUESTIONS_READING } from './DE_7_RAW_QUESTIONS_READING';
import { DE_8_RAW_QUESTIONS_READING } from './DE_8_RAW_QUESTIONS_READING';
import { DE_9_RAW_QUESTIONS_READING } from './DE_9_RAW_QUESTIONS_READING';
import { DE_10_RAW_QUESTIONS_READING } from './DE_10_RAW_QUESTIONS_READING';
import { DE_11_RAW_QUESTIONS_READING } from './DE_11_RAW_QUESTIONS_READING';
import { DE_12_RAW_QUESTIONS_READING } from './DE_12_RAW_QUESTIONS_READING';
import { DE_13_RAW_QUESTIONS_READING } from './DE_13_RAW_QUESTIONS_READING';
import { DE_14_RAW_QUESTIONS_READING } from './DE_14_RAW_QUESTIONS_READING';
import { DE_15_RAW_QUESTIONS_READING } from './DE_15_RAW_QUESTIONS_READING';

// Combine all raw reading questions into a single array
export const ALL_RAW_READING_QUESTIONS = [
  ...DE_1_RAW_QUESTIONS_READING,
  ...DE_2_RAW_QUESTIONS_READING,
  ...DE_3_RAW_QUESTIONS_READING,
  ...DE_4_RAW_QUESTIONS_READING,
  ...DE_5_RAW_QUESTIONS_READING,
  ...DE_6_RAW_QUESTIONS_READING,
  ...DE_7_RAW_QUESTIONS_READING,
  ...DE_8_RAW_QUESTIONS_READING,
  ...DE_9_RAW_QUESTIONS_READING,
  ...DE_10_RAW_QUESTIONS_READING,
  ...DE_11_RAW_QUESTIONS_READING,
  ...DE_12_RAW_QUESTIONS_READING,
  ...DE_13_RAW_QUESTIONS_READING,
  ...DE_14_RAW_QUESTIONS_READING,
  ...DE_15_RAW_QUESTIONS_READING,
];
